name: labtech_mobile
description: Aplicativo de Eventos

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.0
  carousel_slider: ^4.2.1
  mobx: ^2.2.1
  json_annotation: ^4.8.1
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  dio: ^5.4.3+1
  get_it: ^7.6.7
  local_auth: ^2.1.8
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^4.2.1
  intl: ^0.18.1
  mobx_codegen: ^2.6.1
  flutter_mobx: ^2.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
       - assets/images/girl.png
       - assets/icons/favicon.ico
       - assets/icons/iconFacebook.png
       - assets/icons/
       - assets/images/
   

